<yerlesim>
    orientation: "vertical"
    padding: 20
    spacing: 3
    Button:
        text: "Dolar"
    Button:
        text: "Euro"
    Button:
        text: "Gram Altın"
    Button:
        text: "Bitcoin"
    Button:
        text: "Çeyrek Cumhuriyet Altını"
    Button:
        text: "Yarım Cumhuriyet Altını"
    Button:
        text: "Tam Cumhuriyet Altını"
    Button:
        text: "Ons Cumhuriyet Altını"
    Button:
        text: "Türk Lirası"
